### ISSUE TITLE
草莓的模型有奇怪的透明边缘

### ISSUE THREAD

**Issue by NiYanhhhhh** [SUIBING112233/AdvancedAgriculture#17]
![2022-12-18_20 49 45](https://user-images.githubusercontent.com/55988662/208299480-0f1ad4bd-974e-4a6f-bbd6-b2b40b590e8b.png)

**Comment by SUIBING112233** [comment]
看上去像是奇怪的模型切边导致的问题，晚点会重新生成模型试试

**Comment by SUIBING112233** [comment]
查明原因是材质没有清理干净，现在已经修复了
