### ISSUE TITLE
🐞 Bug: 最近的几个构建都无法正常运行

### ISSUE THREAD

**Issue by gundami** [SUIBING112233/AdvancedAgriculture#20]
[crash-2023-02-03_20.39.51-client.txt](https://github.com/SUIBING112233/AdvancedAgriculture/files/10578911/crash-2023-02-03_20.39.51-client.txt)
报错都一致

**Comment by SUIBING112233** [comment]
在 [`af18d463ea0c2b10c7b3a988726a51c4861a1aef`](https://github.com/SUIBING112233/AdvancedAgriculture/commit/af18d463ea0c2b10c7b3a988726a51c4861a1aef) 修复。

具体原因为：因为一直在开发环境之中测试，没有及时添加 `Access Widener` 文件到 `fabric.mod.json` 之中。现在已经修复。

顺便这是第200个commit XD
