### ISSUE TITLE
关于Wiki Book中的Title问题

### ISSUE THREAD

**Issue by AmarokIce** [SUIBING112233/AdvancedAgriculture#7]
早安！
我注意到Wiki中 [Why this mod](https://krysztal.gitbook.io/advanced-agriculture/about/why-this-mod) 简介是"这个模组是做什么的？" ，那么恐怕标题应该是What this mod do或者What this mod do咩...
Why this mod 被解释为 “为什么选择这个模组” , Why没有解释“为什么”和“相关原因或反对意见”之外的更多的延伸意义。

**Comment by SUIBING112233** [comment]
很抱歉这么晚才看到。

是个很棒的建议，感觉这方面更适合由专业人士来写XD

在后面有空会改的哦

**Comment by SUIBING112233** [comment]
该问题已经修正，感谢提出
